// SPDX-License-Identifier: AGPL-3.0-only
import { expect, test } from '../offline';
import { piPage } from './pi-fixture';

test('Pi settings uses a navigation card and persistent rail and saves account instructions without losing a chat draft', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await piPage(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  await page.getByTestId('pi-settings-button').click();
  await expect(page.getByTestId('pi-settings')).toBeVisible();
  await page.getByRole('tab', { name: 'Instructions', exact: true }).click();
  await expect(page.getByTestId('pi-instructions')).toHaveValue('');
  await page.getByTestId('pi-instructions').fill('# Preferences\nKeep responses concise. 日本語も使えます。');
  await expect(page.getByTestId('pi-home-button')).toBeEnabled();
  await page.getByRole('tab', { name: 'Providers', exact: true }).click();
  await page.getByRole('tab', { name: 'Instructions', exact: true }).click();
  await expect(page.getByTestId('pi-instructions')).toContainText('日本語');
  await page.getByTestId('pi-home-button').click();
  await expect(page.getByTestId('pi-prompt')).toBeEnabled();
  await page.getByTestId('pi-settings-button').click();
  await expect(page.getByTestId('pi-instructions')).toContainText('日本語');
  await page.getByTestId('window-close-pi').click();
  await expect(page.getByTestId('server-app-confirm')).toContainText('unsaved settings');
  await page.getByTestId('server-app-confirm').getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('region', { name: 'Agent instructions', exact: true }).getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByTestId('pi-notification')).toHaveText('Saved');
  await expect(page.getByRole('region', { name: 'Agent instructions', exact: true }).getByRole('status')).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Instruction file' })).toHaveCount(0);
  await expect(page.getByTestId('pi-append-instructions')).toHaveValue('');
  await expect(page.getByTestId('pi-settings')).toContainText('/home/user/.pi/agent/APPEND_SYSTEM.md');
  await page.getByTestId('pi-append-instructions').fill('Additional independent draft');
  await page.getByTestId('pi-instructions').fill('Another agent draft');
  const additional = page.getByRole('region', { name: 'Additional system instructions', exact: true });
  await additional.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByTestId('pi-notification')).toHaveText('Saved');
  await expect(additional.getByRole('status')).toHaveCount(0);
  await expect(page.getByTestId('pi-instructions')).toHaveValue('Another agent draft');
  await page.getByRole('region', { name: 'Agent instructions', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByTestId('pi-instructions')).toContainText('日本語');
  await expect(page.getByTestId('pi-append-instructions')).toHaveValue('Additional independent draft');
  await expect(page.getByTestId('pi-sidebar')).toHaveCount(0);
  const app = (await page.getByTestId('app-pi').boundingBox())!;
  const settings = (await page.getByTestId('pi-settings').boundingBox())!;
  const rail = (await page.getByTestId('pi-app-rail').boundingBox())!;
  expect(settings.x).toBe(app.x + rail.width); expect(settings.width).toBe(app.width - rail.width);
  await page.mouse.move(1400, 900);
  await page.screenshot({ path: '/tmp/lumo-pi-settings-light.png', animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: '/tmp/lumo-pi-settings-dark.png', animations: 'disabled' });
  await page.getByTestId('pi-home-button').click();
  await expect(page.getByTestId('pi-prompt')).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Connect provider', exact: true })).toBeHidden();
  await page.getByTestId('pi-prompt').fill('Keep this unsent message');
  await page.getByTestId('pi-settings-button').click();
  await expect(page.getByTestId('pi-instructions')).toContainText('日本語');
  await page.getByTestId('pi-home-button').click();
  await expect(page.getByTestId('pi-prompt')).toHaveText('Keep this unsent message');
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click();
  await page.getByTestId('pi-settings-button').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByTestId('pi-instructions')).toBeVisible();
  await page.screenshot({ path: '/tmp/lumo-pi-settings-narrow.png', animations: 'disabled' });
  expect(errors).toEqual([]);
});

test('Pi settings keeps a draft on save conflict and can reload server changes', async ({ page }) => {
  await piPage(page);
  let external = false;
  await page.route('**/api/v1/pi/settings**', (route) => {
    if (route.request().method() === 'POST') { external = true; return route.fulfill({ status: 409, json: { ok: false, error: { code: 'conflict', message: 'Instructions changed on the server. Reload before saving.' } } }); }
    if (!external) return route.fallback();
    return route.fulfill({ json: { ok: true, data: { kind: 'instructions', path: '/home/user/.pi/agent/AGENTS.md', content: 'Changed over SSH', revision: 'new-revision', exists: true } } });
  });
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  await page.getByTestId('pi-settings-button').click();
  await page.getByRole('tab', { name: 'Instructions', exact: true }).click();
  await page.getByTestId('pi-instructions').fill('My pending changes');
  await page.getByRole('region', { name: 'Agent instructions', exact: true }).getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('changed on the server');
  await expect(page.getByTestId('pi-notification')).toHaveCount(0);
  await expect(page.getByTestId('pi-instructions')).toHaveValue('My pending changes');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Reload instructions', exact: true }).click();
  await expect(page.getByTestId('pi-instructions')).toHaveValue('Changed over SSH');
});

test('Pi keeps Home and Settings at opposite rail ends and supports vertical keyboard tabs', async ({ page }) => {
  const fixture = await piPage(page);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  await expect(page.getByTestId('pi-prompt')).toBeEnabled();
  await page.getByTestId('pi-prompt').fill('Keep the chat draft');
  const home = page.getByTestId('pi-home-button'); const settings = page.getByTestId('pi-settings-button');
  const homeBox = (await home.boundingBox())!; const settingsBox = (await settings.boundingBox())!;
  expect(settingsBox.y).toBeGreaterThan(homeBox.y + 200);
  expect(settingsBox.x).toBe(homeBox.x);
  await settings.click();
  await expect(settings).toHaveAttribute('aria-current', 'page');
  await expect(page.getByRole('button', { name: 'Back', exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Providers', exact: true }).focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('tab', { name: 'Instructions', exact: true })).toBeFocused();
  await expect(page.getByRole('tab', { name: 'Instructions', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByTestId('pi-instructions').fill('Unfinished settings draft');
  await home.click();
  await expect(home).toHaveAttribute('aria-current', 'page');
  await expect(page.getByTestId('pi-prompt')).toHaveText('Keep the chat draft');
  await settings.click();
  await expect(page.getByTestId('pi-instructions')).toHaveValue('Unfinished settings draft');
  expect(fixture.starts).toHaveLength(1);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: '/tmp/lumo-pi-settings-rail-light.png', animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: '/tmp/lumo-pi-settings-rail-dark.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/lumo-pi-settings-rail-narrow.png', animations: 'disabled' });
  expect(await page.getByTestId('app-pi').evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
  await expect(home).toBeVisible(); await expect(settings).toBeVisible();
});


test('Pi keeps sidebar and New chat rail buttons disabled in Settings', async ({ page }) => {
  await piPage(page); await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  await expect(page.getByTestId('pi-prompt')).toBeEnabled();
  const toggle = page.getByTestId('pi-sidebar-toggle');
  await toggle.click();
  const rail = page.getByTestId('pi-app-rail'); const newChat = rail.getByTestId('pi-new');
  const controls = rail.locator('button');
  const before = await controls.evaluateAll((nodes) => nodes.map((node) => { const {x,y,width,height}=node.getBoundingClientRect(); return {x,y,width,height}; }));
  await page.getByTestId('pi-settings-button').click();
  await expect(toggle).toBeVisible(); await expect(toggle).toBeDisabled();
  await expect(newChat).toBeVisible(); await expect(newChat).toBeDisabled();
  await expect(toggle).toHaveCSS('opacity','0.5'); await expect(newChat).toHaveCSS('opacity','0.5');
  expect(await controls.evaluateAll((nodes) => nodes.map((node) => { const {x,y,width,height}=node.getBoundingClientRect(); return {x,y,width,height}; }))).toEqual(before);
  await page.getByTestId('pi-home-button').click();
  await expect(toggle).toBeEnabled(); await expect(newChat).toBeEnabled();
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
  await toggle.click(); await page.getByTestId('pi-settings-button').click();
  await expect(toggle).toBeDisabled(); await expect(newChat).toBeVisible(); await expect(newChat).toBeDisabled();
});
