// SPDX-License-Identifier: AGPL-3.0-only
import { expect, test } from '../offline';
import { attachmentPrompt, expandSkillCommands, splitAttachmentPrompt } from '../../src/apps/piAttachments';
import { piPage } from './pi-fixture';

test('Chat actions are start-only and skills insert inline with keyboard navigation', async ({ page }) => {
  const fixture = await piPage(page);
  await page.route('**/api/v1/skills', (route) => route.fulfill({ json: { ok: true, data: { path: '/home/user/.agents/skills', skills: [{ id: 'review', name: 'review', description: 'Review a change', path: '/home/user/.agents/skills/review/SKILL.md' }], limited: false } } }));
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  const input = page.getByTestId('pi-prompt');
  await expect(input).toBeEnabled();
  await input.fill('/');
  const menu = page.getByTestId('pi-slash-menu');
  await expect(menu).toBeVisible();
  await expect(menu.getByRole('option').filter({ hasText: '/undo' })).toBeDisabled();
  await expect(menu.getByRole('option').filter({ hasText: '/skill:review' })).toBeEnabled();
  await input.press('Escape'); await expect(menu).toHaveCount(0); await expect(input).toHaveText('/');
  await input.fill('Please /rev');
  await expect(menu.getByRole('option')).toHaveCount(1);
  await input.press('Tab'); await expect(input).toHaveText('Please review'); await expect(input).toBeFocused();
  await input.press('Enter');
  await expect.poll(() => fixture.commands.some((item) => item.type === 'prompt' && item.message.includes('"path":"/home/user/.agents/skills/review/SKILL.md"'))).toBe(true);
  await expect(page.getByTestId('pi-messages')).not.toContainText('[Lumo skill references]');
  await expect(page.getByTestId('pi-messages')).toContainText('Please review');
  await expect(page.getByTestId('pi-messages').getByTestId('pi-skill-reference')).toHaveText('review');
  await input.fill('/compact');
  await expect(menu.getByRole('option')).toBeDisabled();
  await page.getByTestId('pi-send').click();
  await expect(page.getByRole('alert')).toContainText('Wait until Pi is idle');
  expect(fixture.commands.filter((item) => item.type === 'compact')).toHaveLength(0);
  await input.fill('Next /rev'); await input.press('Enter'); await input.press('Enter');
  await expect.poll(() => fixture.commands.some((item) => item.type === 'follow_up' && item.message.includes('SKILL.md'))).toBe(true);
  fixture.finish(); await input.fill(''); await expect(page.getByTestId('pi-send')).toHaveAttribute('aria-label', 'Send');
  await input.fill('Discuss /compact'); await expect(menu).toHaveCount(0);
  await input.press('Enter');
  await expect.poll(() => fixture.commands.some((item) => item.type === 'prompt' && item.message === 'Discuss /compact')).toBe(true);
  fixture.finish(); await expect(page.getByTestId('pi-send')).toHaveAttribute('aria-label', 'Send');
  await input.fill('/'); await input.press('ArrowDown'); await input.press('Tab');
  await expect(input.locator('[data-command-token]')).toHaveCount(0);
  await expect(input).toHaveText('');
  await expect(page.getByRole('alertdialog')).toContainText('Rename conversation');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await input.fill('/undo'); await menu.getByRole('option').click();
  await expect(page.getByRole('alertdialog')).toContainText('Edit & resend');
  await expect(input).toHaveText('');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await input.fill('/compact'); await input.press('Enter');
  await expect.poll(() => fixture.commands.filter((item) => item.type === 'compact').length).toBe(1);
  await expect(input).toHaveText('');
  await input.fill('/');
  await expect(menu).toBeVisible();
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
  await page.screenshot({ path: '/tmp/lumo-pi-slash-dark.png', animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.screenshot({ path: '/tmp/lumo-pi-slash-light.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await input.fill(''); await input.fill('/'); await expect(menu).toBeVisible();
  await page.screenshot({ path: '/tmp/lumo-pi-slash-narrow.png', animations: 'disabled' });
  const box = (await menu.boundingBox())!; const app = (await page.getByTestId('app-pi').boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(app.x); expect(box.y).toBeGreaterThanOrEqual(app.y); expect(box.x + box.width).toBeLessThanOrEqual(app.x + app.width);
  await expect(page.locator('.pi-session-actions')).toHaveCount(0);
  expect(errors).toEqual([]);
});


test('Skill references preserve displayed text and attachment round trips', () => {
  const text = 'Review this with /skill:review please';
  const expanded = expandSkillCommands(attachmentPrompt(text, ['/home/user/main.ts']), [{ id: 'review', name: 'review', path: '/home/user/.agents/skills/review/SKILL.md', description: '' }]);
  expect(expanded).toContain('Read the listed SKILL.md files');
  expect(splitAttachmentPrompt(expanded)).toEqual({ text, paths: ['/home/user/main.ts'], references: [], skills: [{ name: 'review', path: '/home/user/.agents/skills/review/SKILL.md' }] });
  expect(expandSkillCommands('https://host/skill:review /home/user', [])).toBe('https://host/skill:review /home/user');
});

test('Completed skills are atomic tokens and preserve multiline text, paste and editing undo', async ({ page }) => {
  await piPage(page);
  await page.route('**/api/v1/skills', (route) => route.fulfill({ json: { ok: true, data: { skills: [{ id: 'review', name: 'review', description: 'Review a change', path: '/home/user/.agents/skills/review/SKILL.md' }] } } }));
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  const input = page.getByTestId('pi-prompt'); await expect(input).toBeEnabled();
  await input.fill('Please /rev'); await input.press('Tab');
  const chip = input.locator('[data-command-token]'); await expect(chip).toHaveText('review');
  await expect(chip).toHaveAttribute('data-command-token', '/skill:review');
  await expect(chip).toHaveAttribute('contenteditable', 'false'); await expect(chip.locator('svg')).toHaveCount(1);
  await input.press('Backspace'); await expect(chip).toHaveCount(0); await expect(input).toHaveText('Please');
  await input.press('ControlOrMeta+z'); await expect(chip).toHaveCount(1);
  await input.pressSequentially('for this'); await input.press('Shift+Enter'); await input.pressSequentially('Second line');
  expect(await input.textContent()).toBe('Please review for this\nSecond line');
  await input.evaluate((node) => { const data = new DataTransfer(); data.setData('text/plain', '\n<safe>'); data.setData('text/html', '<img src=x onerror=alert(1)>'); node.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: data })); });
  await expect(input).toContainText('<safe>'); await expect(input.locator('img')).toHaveCount(0);
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
  await page.screenshot({ path: '/tmp/lumo-pi-skill-token.png', animations: 'disabled' });
  await input.fill('/compact /skill:review');
  await expect(input.locator('[data-command-token]')).toHaveCount(1);
  await expect(input.locator('[data-command-token]')).toHaveText('review');
  await page.screenshot({ path: '/tmp/lumo-pi-colored-tokens-dark.png', animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.screenshot({ path: '/tmp/lumo-pi-colored-tokens-light.png', animations: 'disabled' });
  await input.fill('/skill:review other text'); await input.evaluate((node) => window.getSelection()?.collapse(node, 0)); await input.press('Delete');
  await expect(chip).toHaveCount(0); await expect(input).toHaveText('other text');
  await input.click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Undo', exact: true }).click();
  await expect(chip).toHaveText('review');
  await page.locator('[data-menu-button=edit]').click();
  await page.getByTestId('menu-select-all').click();
  expect(await page.evaluate(() => window.getSelection()?.toString())).toBe('review other text');
});

test('Saved user messages keep skill chips without the current skill catalog', async ({ page, context }) => {
  await piPage(page);
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://localhost:5200' });
  const skill = { id: 'code_review', name: 'code_review', path: '/home/user/.agents/skills/code_review/SKILL.md', description: '' };
  const text = 'Use /skill:code_review with **care**.\n\nKeep `/skill:code_review` as an example and /skill:unknown as text.';
  const prompt = expandSkillCommands(text, [skill]);
  await page.route('**/api/v1/skills', (route) => route.fulfill({ json: { ok: true, data: { skills: [] } } }));
  await page.route('**/api/v1/pi/command', (route) => route.request().postDataJSON().command.type === 'get_messages' ? route.fulfill({ json: { ok: true, data: { success: true, eventCursor: 0, data: { messages: [{ role: 'user', content: prompt }, { role: 'assistant', content: '/skill:code_review is quoted here.' }] } } } }) : route.fallback());
  await page.goto('http://localhost:5200'); await page.getByTestId('dock-app-pi').click();
  const message = page.getByRole('article', { name: 'Your message' });
  const chip = message.getByTestId('pi-skill-reference');
  await expect(chip).toHaveCount(1); await expect(chip).toHaveText('code_review');
  await expect(chip.locator('svg')).toHaveCount(1);
  await expect(chip).toHaveCSS('background-color', 'color(srgb 0.156863 0.458824 0.407843 / 0.1)');
  await expect(message.locator('strong')).toHaveText('care');
  await expect(message.locator('code')).toHaveText('/skill:code_review');
  await expect(message).toContainText('/skill:unknown');
  await expect(message).not.toContainText('[Lumo skill references]');
  await expect(page.getByRole('article', { name: 'Pi response' }).getByTestId('pi-skill-reference')).toHaveCount(0);
  await message.hover(); await message.getByRole('button', { name: 'Copy message' }).click();
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(text);
  await page.screenshot({ path: '/tmp/lumo-sent-skills-light.png', animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: '/tmp/lumo-sent-skills-dark.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(chip).toBeVisible();
  expect(await message.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
});
